name: 'Hello World JS Action'
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string

      jobs:
my-job:
  # Importing a reusable workflow from another repository and branch
  uses: organization/repo/.github/workflows/build-test-deploy.yml@main
  # Passing 'node-version' as an input parameter to the reusable workflow
  with:
    node-version: '18.x'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run Hello World JS Action
      run: node index.js
      env:
        WHO_TO_GREET: ${{ inputs.who-to-greet }}
